### ISSUE TITLE
[BUG] paho basic test failed sometimes

### ISSUE THREAD

**Issue by before30** [kumquatt/mqttd#12]
Sometime failed the paho basic test,

**Comment by before30** [comment]
-> python3 client_test.py localhost 1883
hostname localhost port 1883
clean up starting
clean up finished
Basic test starting
2
[('TopicA', b'qos 1', 2, False, 1), ('TopicA', b'qos 2', 2, False, 2)]
Traceback (most recent call last):
  File "client_test.py", line 109, in basic_test
    assert len(callback.messages) == 3
AssertionError
ERROR:root:receive: unexpected exception (<class 'ConnectionResetError'>, ConnectionResetError(54, 'Connection reset by peer'), <traceback object at 0x10cf4fac8>)
Traceback (most recent call last):
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/client/internal.py", line 44, in receive
    packet = MQTTV3.unpackPacket(MQTTV3.getPacket(self.socket))
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/formats/MQTTV311.py", line 62, in getPacket
    buf = aSocket.recv(1) # get the first byte fixed header
ConnectionResetError: [Errno 54] Connection reset by peer
ERROR:root:call: unexpected exception (<class 'ConnectionResetError'>, ConnectionResetError(54, 'Connection reset by peer'), <traceback object at 0x10cf924c8>)
Traceback (most recent call last):
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/client/internal.py", line 155, in **call**
    self.receive(callback)
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/client/internal.py", line 44, in receive
    packet = MQTTV3.unpackPacket(MQTTV3.getPacket(self.socket))
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/formats/MQTTV311.py", line 62, in getPacket
    buf = aSocket.recv(1) # get the first byte fixed header
ConnectionResetError: [Errno 54] Connection reset by peer
Basic test failed
Basic test starting
4
[('TopicA', b'qos 1', 2, False, 1), ('TopicA', b'qos 2', 2, False, 2), ('TopicA', b'qos 2', 2, False, 1), ('TopicA', b'qos 1', 2, False, 2)]
Traceback (most recent call last):
  File "client_test.py", line 109, in basic_test
    assert len(callback.messages) == 3
AssertionError
ERROR:root:receive: unexpected exception (<class 'ConnectionResetError'>, ConnectionResetError(54, 'Connection reset by peer'), <traceback object at 0x10cf79448>)
Traceback (most recent call last):
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/client/internal.py", line 44, in receive
    packet = MQTTV3.unpackPacket(MQTTV3.getPacket(self.socket))
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/formats/MQTTV311.py", line 62, in getPacket
    buf = aSocket.recv(1) # get the first byte fixed header
ConnectionResetError: [Errno 54] Connection reset by peer
ERROR:root:call: unexpected exception (<class 'ConnectionResetError'>, ConnectionResetError(54, 'Connection reset by peer'), <traceback object at 0x10cf924c8>)
Traceback (most recent call last):
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/client/internal.py", line 155, in **call**
    self.receive(callback)
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/client/internal.py", line 44, in receive
    packet = MQTTV3.unpackPacket(MQTTV3.getPacket(self.socket))
  File "/Users/before30/kumquatt/org.eclipse.paho.mqtt.testing/interoperability/mqtt/formats/MQTTV311.py", line 62, in getPacket
    buf = aSocket.recv(1) # get the first byte fixed header
ConnectionResetError: [Errno 54] Connection reset by peer
Basic test failed
test suite failed

**Comment by before30** [comment]
Paho test has some bugs
You should clear the callback buffer before publishing and after assert
